[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "python312Packages.setuptools"]

[phases.install]
cmds = [
  "pip3.12 install -r requirements.txt || pip install -r requirements.txt || python3.12 -m pip install -r requirements.txt"
]

[start]
cmd = "uvicorn server:app --host 0.0.0.0 --port $PORT --workers 2"

